# Generated by Django 4.0.3 on 2022-04-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums_analyses', '0002_add_timestamps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumanalysis',
            options={'verbose_name_plural': 'Album Analyses'},
        ),
    ]
