# Generated by Django 4.0.3 on 2022-04-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("albums_analyses", "0003_alter_albumanalysis_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="albumanalysis",
            options={
                "ordering": ["created_at"],
                "verbose_name_plural": "Album Analyses",
            },
        ),
    ]
