# Generated by Django 4.0.3 on 2022-04-09 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('mbid', models.CharField(db_index=True, max_length=36, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('cover', models.CharField(max_length=100, null=True)),
                ('album_type', models.CharField(choices=[('LP', 'LP'), ('EP', 'EP'), ('UK', 'Unknown')], default='LP', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('track_number', models.PositiveIntegerField()),
                ('lyrics', models.TextField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbid', models.CharField(db_index=True, max_length=36, null=True)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=150, null=True)),
                ('albums', models.ManyToManyField(blank=True, related_name='artists', to='albums.album')),
            ],
        ),
    ]
