# Generated by Django 4.0.3 on 2022-04-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_albums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='mbid',
            field=models.CharField(db_index=True, max_length=36, null=True, unique=True),
        ),
    ]
